before:
  hooks:
    - go mod download
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - windows
      - darwin
      - linux
    ignore:
      - goos: darwin
        goarch: 386
    ldflags:
      - -X github.com/superfly/flyctl/flyctl.BuildDate={{.Date}}
      - -X github.com/superfly/flyctl/flyctl.Version={{ .Version }}
      - -X github.com/superfly/flyctl/flyctl.Commit={{ .ShortCommit }}
      - -X github.com/superfly/flyctl/flyctl.Environment=production
archives:
  - replacements:
      darwin: macOS
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    files: [only-the-binary*]
    wrap_in_directory: false
    format: tar.gz
  - id: binary
    format: binary
    files: [only-the-binary*]
    replacements:
      darwin: macOS
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
release:
  prerelease: auto
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
